version: "3.8"

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    image: elasticsearch-with-plugins
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - appnet

  pubsubemulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
    networks:
      - appnet

  fake-gcs-server:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    volumes:
      - ./data/gcs:/storage
    command: -scheme http -public-host ${URL:-localhost}:4443
    networks:
      - appnet

  sync:
    build:
      context: .
      dockerfile: Dockerfile.sync
    environment:
      - STORAGE_EMULATOR_HOST=fake-gcs-server:4443
      - PUBSUB_EMULATOR_HOST=pubsubemulator:8085
      - GCP_PROJECT_ID=wakuwaku
    depends_on:
      - pubsubemulator
      - fake-gcs-server
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
